services:
  # MongoDB 8
  mongodb:
    image: mongo:8
    container_name: training-app-mongodb-dev
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoUser
      MONGO_INITDB_ROOT_PASSWORD: mongoPass
      MONGO_INITDB_DATABASE: training-app
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data_dev:/data/db
    networks:
      - training-app-network-dev
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: redis:latest
    container_name: training-app-redis-dev
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data_dev:/data
    networks:
      - training-app-network-dev
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # NestJS Application - Development Mode
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: training-app-dev
    restart: unless-stopped
    environment:
      # App Config
      NODE_ENV: development
      PORT: 3000
      SERVICE_NAME: training-app

      # Database Config
      DB_HOST: mongodb
      DB_PORT: 27017
      DB_USERNAME: mongoUser
      DB_PASSWORD: mongoPass
      DB_DATABASE: training-app

      # Logger Config
      LOG_LEVEL: debug
      LOG_FORMAT: pretty
      LOG_INCLUDE_TIMESTAMP: true
    ports:
      - '3000:3000'
    volumes:
      # Mount source code for hot reload
      - ./src:/app/src:z
      # Prevent overwriting node_modules
      - /app/node_modules
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - training-app-network-dev

volumes:
  mongodb_data_dev:
    driver: local
  redis_data_dev:
    driver: local

networks:
  training-app-network-dev:
    driver: bridge